# Use official Python image
FROM python:3.13

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Collect static files (for Django)
RUN python manage.py collectstatic --noinput

# Expose port 8000
EXPOSE 8000

CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 0 notGoodReads.wsgi:application
