# Use official Python image
FROM python:3.13

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Collect static files (for Django)
RUN python manage.py collectstatic --noinput

# Run migrations (for Django)
RUN python manage.py migrate

# Expose port 8000
EXPOSE 8000

# Start Django server  MYPROJECT.WSGI É PLACEHOLDERRRRRRRRRR
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi"]
